# Generated by Django 3.1.4 on 2020-12-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('ingredient_1', models.CharField(max_length=50)),
                ('ingredient_2', models.CharField(max_length=50)),
                ('ingredient_3', models.CharField(max_length=50)),
                ('ingredient_4', models.CharField(max_length=50)),
                ('ingredient_5', models.CharField(max_length=50)),
            ],
        ),
    ]
