# Generated by Django 3.1.4 on 2020-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('diet_type_1', models.CharField(max_length=255)),
                ('diet_type_2', models.CharField(max_length=255)),
                ('diet_type_3', models.CharField(max_length=255)),
                ('diet_type_4', models.CharField(max_length=255)),
                ('diet_type_5', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_5',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='recipe_name',
            field=models.CharField(max_length=255),
        ),
    ]

